config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
    resources :costs
    resources :categories do
	  resources :incomes
	  resources :costs
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :incomes
  has_many :costs
  belongs_to :user
  validates :name, presence: true
  
  def incomes_total
    total = 0
    incomes.each do |income|
      total += income.amount
    end
    total
  end
  
  def costs_total
    total = 0
    costs.each do |cost|
      total += cost.amount
    end
    total
  end
end

app/models/cost.rb
class Cost < ActiveRecord::Base
    belongs_to :category
    validates :amount, presence: true, numericality: true
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :category 
  validates :amount, presence: true, numericality: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :categories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def total_income
    total = 0
    categories.each do |category|
      total += category.incomes_total
    end
    total
  end
  
  def total_cost
    total = 0
    categories.each do |category|
      total += category.costs_total
    end
    total
  end
  
  def total_balance
    self.total_income + self.total_cost
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  def after_sign_in_path_for(resource)
    sign_in_url = new_user_session_url
    if request.referer == sign_in_url
      super
    else
      stored_location_for(resource) || categories_path || root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    if params[:date].values.join.blank?
      date = Date.today
    else
      date   = params[:date].values.join("/").to_date
    end
    
    name   = params[:name]
    amount = params[:amount].to_i
    
    @category = Category.new(name: name, date: date, user_id: current_user.id)
    
    if @category.save
      if amount > 0
        Income.create(amount: amount, category_id: @category.id)
      else
        Cost.create(amount: amount, category_id: @category.id)
      end
    
      redirect_to categories_path
    else
      @categories = current_user.categories
      render :index
    end

  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
    
    def record_params
      params
    end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @category = Category.find(params[:category_id])
    @cost   = Cost.new(cost_params.merge(category_id: params[:category_id]))
    if @cost.save
      respond_to do |format|
        format.html { redirect_to @category, notice: 'Cost was successfully created.' }
      end
    else
      
      render "categories/show"
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    cost = Cost.find(params["id"])
    @category = Category.find(params[:category_id])
    cost.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Cost was successfully deleted.' }
    end 
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:amount, :category_id)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @category = Category.find(params[:category_id])
    @income   = Income.new(income_params.merge(category_id: params[:category_id]))
    if @income.save
      respond_to do |format|
    format.html { redirect_to @category, notice: 'Income was successfully created.' }
      end
    else
      
      render "categories/show"
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @category = Category.find(params[:category_id])
    @income.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Income was successfully deleted.' }
    end 
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_income
    @income = Income.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def income_params
    params.require(:income).permit(:amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Records</h2>

<table width= "904">
  <tr>
    <td><center><h3>Total Income<hr></h3></center><h3><center><%= current_user.total_income %></center></h3></td>
    <td><center><h3>Total Cost<hr></h3></center><h3><center><%= current_user.total_cost %></center></h3></td>
    <td><center><h3>Total Remainig Balance<hr></h3></center><h3><center><%= current_user.total_balance %></center></h3></td>
  </tr>
</table>

<table width= "904">
	<tr>
		<% if current_user.total_balance <0 %>
			<h><b>Your total balance is runing low. Please look into your expenses</b></h>   
				<br>
		<% end %>
	</tr>
<% if @category %>
  <% if @category.errors.size > 0 %>
    <div id="error_explanation">
      <%- if @category.errors %>
        <%= @category.errors.full_messages.join(", ") %>
      <% end %>
    </div>
  <% end %>
<% end %>
  <tr>
    <td>
      <%= form_tag "/categories/", method: :post do %>
        <%= label_tag :date %>
        <%= date_select("date", "on", prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }) %>
        <%= label_tag :name %>
        <%= text_field_tag :name %>
        <%= label_tag :amount %>
        <%= text_field_tag :amount %>
        <%= submit_tag "Create Record" %>
      <% end %>
    </td>
  </tr>
</table>

<table width= "904">
  <tbody>
    <%- @categories.each do |category| %>
      <%- category.incomes.each do |income| %>
        <tr>
          <td>
            <%- if category.date %>
              <%= category.date.strftime("%m/%d/%Y") %>
            <% else %>
              <%= income.created_at.strftime("%m/%d/%Y")  %>
            <% end %>
          </td>
          <td>
            <%= category.name %>
          </td>
	        <td>
	          <%= income.amount %>	
          </td>
          <td>
	          <%= link_to 'Destroy', "/categories/#{category.id}/incomes/#{income.id}", 
		          method: :delete, data: { confirm: 'Are you sure?' } %>
	        </br>
	        </td>
        </tr>
      <% end %>
      <%- category.costs.each do |cost| %>
        <tr>
          <td>
            <% if category.date %>
              <%= category.date.strftime("%m/%d/%Y") %>
            <% else %>
              <%= cost.created_at.strftime("%m/%d/%Y") %>
            <% end %>
          </td>
          <td>
            <%= category.name %>
          </td>
	        <td>
	          <%= cost.amount %>	
          </td>
          <td>
	          <%= link_to 'Destroy', "/categories/#{category.id}/costs/#{cost.id}", 
		          method: :delete, data: { confirm: 'Are you sure?' } %>
	        </br>
	        </td>
        </tr>
      <% end %>
	  <% end %>
  </tbody>
</table>
<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<tr>
  <td>
	  <%= form_for [@category, Income.new] do |f| %>
	    <%= f.text_field :amount %>
	    <%= f.submit "Add Income" %>
	  <% end %>
	</td>
</tr>

<%- if @income %>
  <div id="error_explanation">
    <tr>
      <td>
        <%- if @income.errors %>
          <%= @income.errors.full_messages.join(", ") %>
        <% end %>
      </td>
    </tr>
  </div>
<% end %>
  	    
<%- @category.incomes.each do |income| %>
  </br>
  <tr>
    <td>
	  Income
	</td>
	<td>
	  <%= income.amount %>	
    </td>
    <td>
	  <%= link_to 'Destroy', "/categories/#{@category.id}/incomes/#{income.id}", 
		method: :delete, data: { confirm: 'Are you sure?' } %> 
	  </br>
	</td>
  </tr>
<% end %>
<br><tr><td><hr></td></tr>

<tr>
  <td>
    Total Income:
  </td>
  <td>
    <strong>
      <%= @category.incomes_total %>
    </strong>  
  </td>
</tr>

<hr>
<tr>
  <td>
	<%= form_for [@category, Cost.new] do |f| %>
	  <%= f.text_field :amount %>
	  <%= f.submit "Add Cost" %>
	<% end %>
  </td>
</tr>
<%- if @cost %>
  <div id="error_explanation">
    <tr>
      <td>
        <%- if @cost.errors %>
          <%= @cost.errors.full_messages.join(", ") %>
        <% end %>
      </td>
    </tr>
  </div>
<% end %>
<%- @category.costs.each do |cost| %>
  <br>
  <tr> 			
	  <td>
	    Cost
	  </td>
	  <td>
	    <%= cost.amount %>	
	  </td>
	  <td>
	    <%= link_to 'Destroy', "/categories/#{@category.id}/costs/#{cost.id}", 
		    method: :delete, data: { confirm: 'Are you sure?' } %> </br>
	  </td>
  </tr>
<% end %>
<br><tr><td><hr></td></tr>
<tr>
  <td>
    Total Cost:
  </td>
  <td>
    <strong>
      <%= @category.costs_total %>
    </strong>  
  </td>
</tr>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Costs</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.amount %></td>
        <td><%= cost.category_id %></td>
        <td><%= link_to 'Show', cost %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cost', new_cost_path %>

app/views/costs/new.html.erb
<h1>New Cost</h1>

<%= render 'form' %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p>
  <strong>Amount:</strong>
  <%= @cost.amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= @cost.category_id %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Incomes</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.amount %></td>
        <td><%= income.category_id %></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income', new_income_path %>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= @income.category_id %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<style>
body {background-color:lavender}
 h1   {color:purple}
 h2   {color:purple;}
 h3   {color:purple;}
 h    {color:red;}
 
 table, th, td {
			border: 1px solid black;
				}
</style>
	

<body>
  
  <body>
<h1><b><I><center>Expense Tracker</center></I></b></h1>
<p><a href="https://bitbucket.org/ranjitha1992/wallet">wallet app</a></p>
  
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

<% end %>

<%= yield %>

</body>
</html>